#!/usr/bin/env bash
# Generate the RSA key pair
ssh-keygen -t rsa -b 4096 -f ~/.ssh/school -N "betty" -q

# Configure SSH client
cat > ~/.ssh/config <<EOL
Host myserver
  IdentityFile ~/.ssh/school
  PasswordAuthentication no
EOL
