#!/usr/bin/env bash

sudo apt update
sudo apt install nginx

sudo nano /etc/nginx/sites-available/default

server {
    listen 80;
    server_name _;

    root /var/www/html;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ =404;
    }
}

sudo systemctl start nginx

sudo netstat -tuln | grep :80

sudo ufw allow 80/tcp
sudo ufw reload

curl localhost:80

sudo tail -f /var/log/nginx/error.log
