#!/usr/bin/env bash
# Update package lists
sudo apt update -y

# Install Nginx
sudo apt install -y nginx

# Ensure Nginx is listening on port 80
sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default

# Modify the default index.html to contain "Holberton School"
echo "Holberton School says hello hii" | sudo tee /var/www/html/index.html

sudo chown -R "$USER":"$USER" /var/www/html

# Reload Nginx without using systemctl
nginx -s reload


