#!/usr/bin/env bash
# Ensure script is run as root
if [ "$EUID" -ne 0 ]; then
    echo "Please run as root"
    exit 1
fi

# Install Nginx if not installed
sudo apt update -y
sudo apt install -y nginx

# Modify Nginx config with sudo
sudo sed -i '/server_name _;/a \\n    location /redirect_me {\n        return 301 http://honourgod.tech;\n    }' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
